const constants = {
    ACADEMY_MANAGEMENT: 'ACADEMY_MANAGEMENT',
    ADMIN_SYSTEM: 'ADMIN_SYSTEM',
    CLASS_MANAGEMENT: 'CLASS_MANAGEMENT',
    MAJOR_MANAGEMENT: 'MAJOR_MANAGEMENT',
    ROLE_MANAGEMENT: 'ROLE_MANAGEMENT',
    STUDENT_MANAGEMENT: 'STUDENT_MANAGEMENT',
    TEACHER_MANAGEMENT: 'TEACHER_MANAGEMENT'
}

export default constants
